###
# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
bgp:
  asNumber: 209
  enabled: true
  name: calico-global-bgp-peer
  peerIP: 192.168.5.5
ippool:
  cidr: 10.0.0.0/8
  enabled: true
  name: calico-ip-pool
nameOverride: "calico"
status:
  enabled: true
  name: calico-node-status
  node: kcp01.breeze-blocks.net
testing:
  enabled: false
