{{ if .Values.bgp.enabled }}
{{- range $.Values.bgp.peers }}
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: {{ .name }}
spec:
  peerIP: {{ .peerIP }}
  asNumber: {{ .asNumber }}
  nodeToNodeMeshEnabled: {{ .enableNodeToNodeMesh }}
{{ end }}
{{ end }}
---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  peerIP: 192.168.5.5
  asNumber: 65000
