{{ if .Values.status.enabled }}
apiVersion: crd.projectcalico.org/v1
kind: CalicoNodeStatus
metadata:
  name: {{ .Values.status.name }}
spec:
  classes:
    - Agent
    - BGP
    - Routes
  node: {{ .Values.status.node }}
  updatePeriodSeconds: 10
{{ end }}
